---
- hosts: webservers
  remote_user: ubuntu
  become: yes
  gather_facts: no
  vars:
    www_port: 80
  tasks:
   - name: enabled mod_rewrite
     apache2_module: name=rewrite state=present
     notify:
        restart apache2

   - name: apache2 listen on port 8081
     lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 8081" state=present
     notify:
        - restart apache2

  handlers:
   - name: restart apache2
     service: name=apache2 state=restarted
